### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by dotcologne** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#9]
The rate limit of 50 certificates per subscription doesn't work for us and it was also a pretty bad and unexpected surprise. Now we have to create additional certificates manually and of course this breaks the organisation process flow. If this limit cannot be raised to the number of bindings supported by Azure WebApps (currently 500), we'll have to look for another solution.

**Comment by rcladmin** [comment]
The Let's Encrypt API also institutes rate limits : https://letsencrypt.org/docs/rate-limits/ to allow fair usage by as many as possible. We also follow this philosophy. You may eventually hit the weekly API rate limits for your domain as described in this link. You can consider the following work around:

1. Split your workload into multiple (10) subscriptions (50 web apps for each subscription).
2.  Stagger the creation of certificates (1-2 weeks apart) on the same domain to avoid the API rate limit of 50 per week.

**Comment by dotcologne** [comment]
Dear rcladmin, 

The rate limitation by Let's Encrypt is not relevant in my case as it refers to 50 "Certificates per Registered Domain". But I have 50+ DIFFERENT domains (even different TLDs like com/de/at/ch/net).

Regarding your workaround proposals, I don't understand how this could work. 
1. What do you exactly mean with "subscriptions", Azure subscriptions or Lets-Encrypt-Auto subscriptions? 'Cause the latter I tried already, but received the same error, potentially because I still need to deploy the ceritificates to my one and only WebApp instance. Accordingly I cannot split my WebApp, it's just a single instance resp. Azure WebApp resource.
2. I expected that today I would be able to create certificates again - as it's Monday today. But today I get another error:
![grafik](https://user-images.githubusercontent.com/8538077/81556682-08776100-938b-11ea-91c0-eb273537d894.png)

**Comment by rcladmin** [comment]
Our app Let's Encryot Auto also has Rate Limits to allow for fair usage:

![Capture](https://user-images.githubusercontent.com/4339259/81581529-db23b680-937c-11ea-932f-61bbe795f00a.PNG)

You will need to create additional Let's Encrypt Auto subscriptions to handle more than 50 certificates. If your web apps are in different azure accounts, you can create separate Lets Encrypt Auto subscriptions.

If your web apps are in the same azure account, you can try the following:

1. Create a new user in Active Directory in the azure account
2. Ensure the user is granted permission to manage your azure resources
3. Login to the azure account with this new user account
4. Subscribe to Let's Encrypt Auto with this user account

You can create additional users and creates separate Let's Encrypt Accounts for each batch of 50 SSL/TLS certificate.

5. Stagger creation of SSL/TLS certificate so that you do not hit Lets Encrypt V2 API of 50 certificates/domain/week
